/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package c6;

import java.util.List;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        System.out.println(new App().getGreeting());
    }

    public long wordsThatStartWithE(List<String> words) {
    return words.stream().filter(s -> s.startsWith("e") || s.startsWith("E") ).count();
    }
}
